# from Attack_Code.Combinatorial.attacks.parsimonious_attack import ParsimoniousAttack

from Attack_Code.Combinatorial.attacks.parsimonious_attack_madry import ParsimoniousAttack
# from Attack_Code.Combinatorial.attacks.parsimonious_attack_3_restarts import ParsimoniousAttack_restarts
